require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('./src/config/db');
const Product = require('./src/models/Product');

const products = [
  // ── Finished Products ──────────────────────────────────────────────
  {
    _id: 'fp1',
    name: 'OCLA Glow Body Butter',
    category: 'Finished Products',
    badge: 'Best Seller',
    units: [{ label: '250ml', price: 4500 }, { label: '500ml', price: 8000 }],
    image: '/images/fp1.jpg',
    description: 'A luxurious whipped body butter enriched with shea, mango, and cocoa butter to deeply nourish and restore your skin\'s natural glow.',
    inci: 'Butyrospermum Parkii (Shea) Butter, Mangifera Indica (Mango) Seed Butter, Theobroma Cacao (Cocoa) Seed Butter, Simmondsia Chinensis (Jojoba) Seed Oil, Tocopherol (Vitamin E)',
    grade: 'Cosmetic Grade',
    shelfLife: '12 months unopened',
    storage: 'Store in a cool, dry place away from direct sunlight.',
    safety: 'For external use only. Avoid contact with eyes. Discontinue use if irritation occurs.',
    usageInstructions: 'Apply generously to skin after bathing and massage until absorbed.',
    features: ['Deeply moisturising', 'Non-greasy formula', 'Suitable for all skin types', 'Vegan-friendly'],
  },
  {
    _id: 'fp2',
    name: 'OCLA Radiance Face Serum',
    category: 'Finished Products',
    badge: 'New',
    units: [{ label: '30ml', price: 6500 }],
    image: '/images/fp2.jpg',
    description: 'A brightening face serum with rosehip oil and vitamin C to even skin tone and reduce dark spots.',
    inci: 'Aqua, Niacinamide, Rosa Canina (Rosehip) Fruit Oil, Ascorbic Acid, Aloe Barbadensis Leaf Juice, Hyaluronic Acid',
    grade: 'Cosmetic Grade',
    shelfLife: '12 months unopened',
    storage: 'Store in a cool, dark place. Refrigerate after opening.',
    safety: 'For external use only. Patch test recommended. Avoid eye area.',
    usageInstructions: 'Apply 3–4 drops to cleansed face morning and evening before moisturiser.',
    features: ['Brightening', 'Reduces dark spots', 'Lightweight', 'Suitable for sensitive skin'],
  },
  {
    _id: 'fp3',
    name: 'OCLA Herbal Hair Growth Oil',
    category: 'Finished Products',
    badge: 'Popular',
    units: [{ label: '100ml', price: 3500 }, { label: '200ml', price: 6000 }],
    image: '/images/fp3.jpg',
    description: 'A potent blend of castor, peppermint, and rosemary oils to stimulate hair growth and reduce breakage.',
    inci: 'Ricinus Communis (Castor) Seed Oil, Mentha Piperita (Peppermint) Oil, Rosmarinus Officinalis (Rosemary) Leaf Oil, Argania Spinosa (Argan) Kernel Oil',
    grade: 'Cosmetic Grade',
    shelfLife: '18 months unopened',
    storage: 'Store in a cool, dry place.',
    safety: 'For external use only. Keep away from eyes. Not for internal use.',
    usageInstructions: 'Massage into scalp 2–3 times per week. Leave overnight for best results.',
    features: ['Stimulates growth', 'Reduces breakage', 'Nourishes scalp', 'No mineral oils'],
  },
  {
    _id: 'fp4',
    name: 'OCLA Soothing Body Scrub',
    category: 'Finished Products',
    units: [{ label: '300g', price: 3200 }],
    image: '/images/fp4.jpg',
    description: 'A gentle exfoliating sugar scrub infused with sweet almond oil and lavender essential oil.',
    inci: 'Saccharum Officinarum (Sugar), Prunus Dulcis (Sweet Almond) Oil, Lavandula Angustifolia (Lavender) Oil, Tocopherol',
    grade: 'Cosmetic Grade',
    shelfLife: '12 months unopened',
    storage: 'Store at room temperature. Keep dry.',
    safety: 'For external use only. Avoid broken skin.',
    usageInstructions: 'Apply to damp skin in circular motions, rinse thoroughly.',
    features: ['Gentle exfoliation', 'Moisturising', 'Lavender scent', 'All skin types'],
  },

  // ── Carrier Oils ──────────────────────────────────────────────────
  {
    _id: 'co1',
    name: 'Cold-Pressed Jojoba Oil',
    category: 'Carrier Oils',
    badge: 'Best Seller',
    units: [{ label: '100ml', price: 3200 }, { label: '250ml', price: 7000 }, { label: '500ml', price: 13000 }],
    image: '/images/co1.jpg',
    description: 'Pure cold-pressed jojoba oil, closely resembling skin\'s natural sebum. Ideal for face, hair, and body.',
    inci: 'Simmondsia Chinensis (Jojoba) Seed Oil',
    grade: 'Cosmetic/Food Grade',
    shelfLife: '24 months unopened',
    storage: 'Store in a cool, dark place.',
    safety: 'For external use. Keep out of reach of children.',
    usageInstructions: 'Apply directly to skin or hair, or blend into formulations at 5–100%.',
    features: ['Non-comedogenic', 'Long shelf life', 'Balances sebum', 'Light texture'],
  },
  {
    _id: 'co2',
    name: 'Organic Rosehip Seed Oil',
    category: 'Carrier Oils',
    units: [{ label: '50ml', price: 4500 }, { label: '100ml', price: 8000 }],
    image: '/images/co2.jpg',
    description: 'Rich in vitamins A and C, rosehip oil fades scars and brightens skin tone.',
    inci: 'Rosa Canina Fruit Oil',
    grade: 'Cosmetic Grade',
    shelfLife: '12 months unopened',
    storage: 'Refrigerate after opening.',
    safety: 'For external use only. Patch test recommended.',
    usageInstructions: 'Apply 2–3 drops to face evening only due to vitamin A content.',
    features: ['Anti-ageing', 'Scar fading', 'Rich in vitamins', 'Cold-pressed'],
  },
  {
    _id: 'co3',
    name: 'Virgin Coconut Oil',
    category: 'Carrier Oils',
    units: [{ label: '250ml', price: 2800 }, { label: '500ml', price: 5000 }, { label: '1L', price: 9000 }],
    image: '/images/co3.jpg',
    description: 'Unrefined virgin coconut oil for skin, hair, and cooking.',
    inci: 'Cocos Nucifera (Coconut) Oil',
    grade: 'Food/Cosmetic Grade',
    shelfLife: '24 months unopened',
    storage: 'Store at room temperature (solidifies below 25°C).',
    safety: 'Safe for topical and culinary use.',
    usageInstructions: 'Use as a moisturiser, hair mask, or cooking oil.',
    features: ['Multi-purpose', 'Unrefined', 'Solid at room temp', 'Food-grade'],
  },
  {
    _id: 'co4',
    name: 'Sweet Almond Oil',
    category: 'Carrier Oils',
    units: [{ label: '100ml', price: 2200 }, { label: '250ml', price: 4800 }, { label: '500ml', price: 8500 }],
    image: '/images/co4.jpg',
    description: 'Light, nourishing sweet almond oil perfect for massage, skincare, and haircare.',
    inci: 'Prunus Dulcis (Sweet Almond) Oil',
    grade: 'Cosmetic Grade',
    shelfLife: '18 months unopened',
    storage: 'Store in a cool, dry place.',
    safety: 'Not suitable for those with nut allergies.',
    usageInstructions: 'Apply as massage oil or mix into lotions and serums.',
    features: ['Light texture', 'Great for massage', 'High in vitamin E', 'Gentle on skin'],
  },

  // ── Essential Oils ────────────────────────────────────────────────
  {
    _id: 'eo1',
    name: 'Lavender Essential Oil',
    category: 'Essential Oils',
    units: [{ label: '10ml', price: 2500 }, { label: '30ml', price: 6500 }],
    image: '/images/eo1.jpg',
    description: 'Steam-distilled lavender oil with calming and antibacterial properties.',
    inci: 'Lavandula Angustifolia Oil',
    grade: 'Therapeutic Grade',
    shelfLife: '36 months unopened',
    storage: 'Store in amber glass away from heat and light.',
    safety: 'Always dilute before skin application. Keep from eyes and children.',
    usageInstructions: 'Dilute 2–3% in carrier oil. Add to diffuser for aromatherapy.',
    features: ['Calming', 'Antibacterial', 'Sleep aid', 'Versatile'],
  },
  {
    _id: 'eo2',
    name: 'Peppermint Essential Oil',
    category: 'Essential Oils',
    badge: 'Best Seller',
    units: [{ label: '10ml', price: 2200 }, { label: '30ml', price: 5800 }],
    image: '/images/eo2.jpg',
    description: 'Refreshing peppermint oil ideal for headache relief, hair growth, and muscle soothing.',
    inci: 'Mentha Piperita Oil',
    grade: 'Therapeutic Grade',
    shelfLife: '36 months unopened',
    storage: 'Store in amber glass away from heat.',
    safety: 'Dilute before use. Avoid use on children under 6. Do not use near face of infants.',
    usageInstructions: 'Dilute 1% in carrier oil for scalp or muscle application.',
    features: ['Cooling sensation', 'Stimulates scalp', 'Energising', 'Pain relief'],
  },
  {
    _id: 'eo3',
    name: 'Tea Tree Essential Oil',
    category: 'Essential Oils',
    units: [{ label: '10ml', price: 2800 }],
    image: '/images/eo3.jpg',
    description: 'Powerful antimicrobial tea tree oil for acne, wounds, and scalp health.',
    inci: 'Melaleuca Alternifolia Leaf Oil',
    grade: 'Therapeutic Grade',
    shelfLife: '36 months unopened',
    storage: 'Store in amber glass bottle in a cool place.',
    safety: 'Dilute before use. Do not ingest. Keep away from eyes.',
    usageInstructions: 'Dilute 1–2% in carrier oil or add to shampoo for scalp treatment.',
    features: ['Antimicrobial', 'Acne-fighting', 'Scalp health', 'Natural antiseptic'],
  },
  {
    _id: 'eo4',
    name: 'Rosemary Essential Oil',
    category: 'Essential Oils',
    units: [{ label: '10ml', price: 2500 }, { label: '30ml', price: 6000 }],
    image: '/images/eo4.jpg',
    description: 'Stimulating rosemary essential oil known for hair growth and mental clarity.',
    inci: 'Rosmarinus Officinalis Leaf Oil',
    grade: 'Therapeutic Grade',
    shelfLife: '36 months unopened',
    storage: 'Keep in a cool, dark place.',
    safety: 'Dilute before topical use. Avoid during pregnancy.',
    usageInstructions: 'Add 3–5 drops to shampoo or dilute in carrier oil for scalp massage.',
    features: ['Hair growth', 'Stimulating', 'Mental clarity', 'Antioxidant'],
  },

  // ── Butters ───────────────────────────────────────────────────────
  {
    _id: 'bt1',
    name: 'Raw Shea Butter',
    category: 'Butters',
    badge: 'Best Seller',
    units: [{ label: '250g', price: 2800 }, { label: '500g', price: 5200 }, { label: '1kg', price: 9500 }],
    image: '/images/bt1.jpg',
    description: 'Unrefined Grade A shea butter sourced from West Africa. Rich in vitamins A, E, and F.',
    inci: 'Butyrospermum Parkii (Shea) Butter',
    grade: 'Grade A – Unrefined',
    shelfLife: '24 months unopened',
    storage: 'Store in a cool, dry place.',
    safety: 'For external use. Not suitable if allergic to latex (rare cross-reactivity).',
    usageInstructions: 'Use directly on skin or melt to incorporate into DIY formulations.',
    features: ['Unrefined Grade A', 'Rich in vitamins', 'Deeply moisturising', 'Ethically sourced'],
  },
  {
    _id: 'bt2',
    name: 'Mango Seed Butter',
    category: 'Butters',
    units: [{ label: '250g', price: 3500 }, { label: '500g', price: 6500 }],
    image: '/images/bt2.jpg',
    description: 'Exotic mango seed butter with skin-softening and UV-protective properties.',
    inci: 'Mangifera Indica Seed Butter',
    grade: 'Cosmetic Grade',
    shelfLife: '18 months unopened',
    storage: 'Store in a cool, dark place.',
    safety: 'For external use only.',
    usageInstructions: 'Melt and apply to skin or use in body butter and lotion bars.',
    features: ['Skin softening', 'Mild UV protection', 'Light texture', 'Emollient'],
  },
  {
    _id: 'bt3',
    name: 'Kokum Butter',
    category: 'Butters',
    units: [{ label: '100g', price: 2500 }, { label: '250g', price: 5500 }],
    image: '/images/bt3.jpg',
    description: 'Hard, non-comedogenic kokum butter ideal for lip balms and healing dry cracked skin.',
    inci: 'Garcinia Indica Seed Butter',
    grade: 'Cosmetic Grade',
    shelfLife: '24 months unopened',
    storage: 'Store at room temperature.',
    safety: 'For external use only.',
    usageInstructions: 'Melt before use or add up to 5% to formulations for hardness.',
    features: ['Non-comedogenic', 'Healing', 'Hard butter', 'Great for lip products'],
  },
  {
    _id: 'bt4',
    name: 'Cocoa Butter (Deodorised)',
    category: 'Butters',
    units: [{ label: '250g', price: 3000 }, { label: '500g', price: 5500 }, { label: '1kg', price: 9800 }],
    image: '/images/bt4.jpg',
    description: 'Premium deodorised cocoa butter for use in body butters, lotions, and confections.',
    inci: 'Theobroma Cacao Seed Butter',
    grade: 'Food/Cosmetic Grade',
    shelfLife: '24 months',
    storage: 'Store below 20°C to maintain solid form.',
    safety: 'Food and cosmetic safe.',
    usageInstructions: 'Melt and incorporate into your skincare or food recipes.',
    features: ['Deodorised', 'Food-grade', 'Stretch mark reduction', 'Rich emollient'],
  },

  // ── Cacao ─────────────────────────────────────────────────────────
  {
    _id: 'ca1',
    name: 'Raw Cacao Powder',
    category: 'Cacao',
    badge: 'Best Seller',
    units: [{ label: '250g', price: 3500 }, { label: '500g', price: 6500 }, { label: '1kg', price: 12000 }],
    image: '/images/ca1.jpg',
    description: 'Cold-pressed raw cacao powder, packed with antioxidants and minerals. No sugar, no additives.',
    inci: 'Theobroma Cacao Powder',
    grade: 'Food Grade',
    shelfLife: '18 months unopened',
    storage: 'Store in a cool, dry place in an airtight container.',
    safety: 'Food safe. Contains naturally occurring caffeine and theobromine.',
    usageInstructions: 'Add to smoothies, baking, or face masks. 1–2 tbsp per serving.',
    features: ['High antioxidants', 'No additives', 'Rich flavour', 'Superfood'],
  },
  {
    _id: 'ca2',
    name: 'Cacao Nibs',
    category: 'Cacao',
    units: [{ label: '200g', price: 3200 }, { label: '500g', price: 7000 }],
    image: '/images/ca2.jpg',
    description: 'Crushed cacao beans for a crunchy, bitter chocolate addition to granola, smoothies, and baking.',
    inci: 'Theobroma Cacao Bean Pieces',
    grade: 'Food Grade',
    shelfLife: '18 months unopened',
    storage: 'Store in a cool, dry place.',
    safety: 'Food safe.',
    usageInstructions: 'Sprinkle on yoghurt, oatmeal, or blend into smoothies.',
    features: ['Crunchy texture', 'Antioxidant-rich', 'Unsweetened', 'Keto-friendly'],
  },
  {
    _id: 'ca3',
    name: 'Cacao Butter Wafers',
    category: 'Cacao',
    units: [{ label: '250g', price: 4000 }, { label: '500g', price: 7500 }],
    image: '/images/ca3.jpg',
    description: 'Food and cosmetic grade cacao butter wafers with a rich natural chocolate aroma.',
    inci: 'Theobroma Cacao Seed Butter',
    grade: 'Food/Cosmetic Grade',
    shelfLife: '24 months',
    storage: 'Store below 20°C.',
    safety: 'Food and cosmetic safe.',
    usageInstructions: 'Melt for chocolate-making or add to skincare formulations for texture and scent.',
    features: ['Dual-grade', 'Natural chocolate aroma', 'White wafer form', 'Easy to melt'],
  },
];

async function seed() {
  await connectDB();

  await Product.deleteMany({});
  await Product.insertMany(products);

  console.log(`Seeded ${products.length} products successfully.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
